'use client'
import {useEffect,useState} from 'react'
import {getMembership} from '../../../lib/data'

type Member={user_id:string;role:string;users?:{name?:string;email?:string}}
type Invite={id:string;email:string;role:string;expires_at:string;revoked_at?:string|null}
const roles=['driver','counter_sales','sales_representative','operations_manager','branch_manager']

export default function ManagerTeam(){
 const [members,setMembers]=useState<Member[]>([]),[invites,setInvites]=useState<Invite[]>([]),[branch,setBranch]=useState<any>(null),[branchName,setBranchName]=useState(''),[address,setAddress]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState('driver'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{const{client,membership}=await getMembership();const[m,iv,b]=await Promise.all([client.from('company_users').select('user_id,role,users(email,name)').eq('company_id',membership.company_id),client.from('invitations').select('id,email,role,expires_at,revoked_at').eq('company_id',membership.company_id).order('expires_at',{ascending:false}),membership.branch_id?client.from('branches').select('*').eq('id',membership.branch_id).maybeSingle():Promise.resolve({data:null,error:null} as any)]);if(m.error)throw m.error;setMembers((m.data||[]) as Member[]);setInvites(iv.error?[]:iv.data||[]);if(b.data){setBranch(b.data);setBranchName(b.data.name||'');setAddress(b.data.address||'')}}
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[])
 const saveBranch=async()=>{if(!branch)return;setBusy(true);const{client}=await getMembership();const r=await client.from('branches').update({name:branchName,address}).eq('id',branch.id);setMessage(r.error?r.error.message:'Branch saved.');setBusy(false)}
 const invite=async()=>{if(!email)return;setBusy(true);const{client,user,membership}=await getMembership();const r=await client.from('invitations').insert({company_id:membership.company_id,branch_id:membership.branch_id,email,role,token_hash:crypto.randomUUID(),invited_by:user.id,expires_at:new Date(Date.now()+7*864e5).toISOString()});setMessage(r.error?r.error.message:'Invitation created.');if(!r.error){setEmail('');await load()}setBusy(false)}
 const revoke=async(id:string)=>{setBusy(true);const{client}=await getMembership();const r=await client.from('invitations').update({revoked_at:new Date().toISOString()}).eq('id',id);setMessage(r.error?r.error.message:'Invitation revoked.');if(!r.error)await load();setBusy(false)}
 const updateRole=async(id:string,value:string)=>{const{client}=await getMembership();const r=await client.from('company_users').update({role:value}).eq('user_id',id);setMessage(r.error?r.error.message:'Role updated.');if(!r.error)await load()}
 const remove=async(id:string)=>{if(!window.confirm('Remove this member?'))return;const{client}=await getMembership();const r=await client.from('company_users').delete().eq('user_id',id);setMessage(r.error?r.error.message:'Member removed.');if(!r.error)await load()}
 return <main className="shell admin-page"><div className="eyebrow">ROUTEHUB Â· MANAGER</div><h1>Manage team</h1><p className="muted">Manage branch details, employees, roles, and invitations.</p><section className="card form"><h2>Branch details</h2><input value={branchName} onChange={e=>setBranchName(e.target.value)} placeholder="Branch name"/><input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Full branch address"/><button className="primary" disabled={busy||!branch} onClick={saveBranch}>Save branch</button></section><section className="card form"><h2>Invite a team member</h2><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Employee email" type="email"/><select value={role} onChange={e=>setRole(e.target.value)}>{roles.filter(r=>r!=='branch_manager').map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select><button className="primary" disabled={busy||!email} onClick={invite}>Send invitation</button></section><section><h2>Team ({members.length})</h2>{members.map(m=><article className="card team-member" key={m.user_id}><div><strong>{m.users?.name||m.users?.email||'Team member'}</strong><p className="muted">{m.users?.email||''}</p></div><select value={m.role} onChange={e=>updateRole(m.user_id,e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select><button className="assign danger-action" onClick={()=>remove(m.user_id)}>Remove</button></article>)}</section><section><h2>Invitations ({invites.length})</h2>{invites.map(i=><article className="card team-member" key={i.id}><div><strong>{i.email}</strong><p className="muted">{i.role.replaceAll('_',' ')} Â· Expires {new Date(i.expires_at).toLocaleDateString()}</p></div>{i.revoked_at?<span className="muted">Revoked</span>:<button className="assign danger-action" disabled={busy} onClick={()=>revoke(i.id)}>Revoke</button>}</article>)}</section>{message&&<p className="action-feedback feedback-info" role="status">{message}</p>}</main>
}
