-- Incremental migration for individual missions and live dispatch. Safe to run after schema.sql.
alter table routes add column if not exists origin_address text;
alter table routes add column if not exists origin_name text;
alter table routes add column if not exists destination_address text;
alter table routes add column if not exists destination_name text;
alter table routes add column if not exists scheduled_at timestamptz;
alter table routes add column if not exists order_number text;
alter table routes add column if not exists priority text not null default 'normal';
alter table routes add column if not exists previous_route_id uuid references routes(id);
alter table routes add column if not exists driver_confirmed_at timestamptz;
alter table routes add column if not exists updated_version bigint not null default 1;
alter table routes add column if not exists position int not null default 1;
alter table routes drop constraint if exists routes_status_check;
alter table routes add constraint routes_status_check check (status in ('draft','published','active','paused','completed','cancelled'));
alter table route_stops add column if not exists origin_address text;
alter table route_stops add column if not exists origin_name text;
alter table route_stops add column if not exists destination_address text;
alter table route_stops add column if not exists destination_name text;
alter table route_stops add column if not exists scheduled_at timestamptz;
alter table route_stops add column if not exists order_number text;
alter table route_stops add column if not exists priority text not null default 'normal';
alter table route_stops add column if not exists previous_route_id uuid references routes(id);
alter table route_stops add column if not exists driver_confirmed_at timestamptz;
alter table route_stops add column if not exists updated_version bigint not null default 1;
alter table route_stops drop constraint if exists route_stops_type_check;
alter table route_stops add constraint route_stops_type_check check (type in ('pickup','delivery','transfer','return','return_to_branch'));
alter table route_stops drop constraint if exists route_stops_status_check;
alter table route_stops add constraint route_stops_status_check check (status in ('pending','active','paused','completed','issue','cancelled'));
create index if not exists idx_routes_driver_status_position on routes(driver_id,status,scheduled_at);
create index if not exists idx_route_stops_route_position_status on route_stops(route_id,position,status);
create index if not exists idx_route_stops_previous_route on route_stops(previous_route_id);
create table if not exists mission_alerts(id uuid primary key default gen_random_uuid(),company_id uuid not null references companies(id),route_id uuid not null references routes(id),driver_id uuid not null references users(id),message text not null,created_at timestamptz default now(),confirmed_at timestamptz,confirmed_by uuid references users(id));
