create table companies (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz default now());
create table branches (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), name text not null, default_driver_id uuid, created_at timestamptz default now());
create table users (id uuid primary key, email text not null unique, name text, created_at timestamptz default now());
create table platform_manager_approvals (id uuid primary key default gen_random_uuid(), email text not null unique, company_name text not null, approved_by text not null, approved_at timestamptz default now(), revoked_at timestamptz);
create table platform_admins (user_id uuid primary key references users(id), display_name text not null, access_level text not null default 'ceo', created_at timestamptz default now());
create table platform_audit_logs (id uuid primary key default gen_random_uuid(), admin_user_id uuid not null references users(id), action text not null, company_id uuid references companies(id), target_type text, target_id uuid, reason text, created_at timestamptz default now());
create table support_requests (id uuid primary key default gen_random_uuid(), company_id uuid references companies(id), created_by uuid not null references users(id), category text not null check (category in ('bug','missing_feature','question','suggestion')), subject text not null, message text not null, status text not null default 'open' check (status in ('open','in_progress','resolved','closed')), admin_notes text, created_at timestamptz default now(), updated_at timestamptz default now());
create table company_users (company_id uuid references companies(id), user_id uuid references users(id), branch_id uuid references branches(id), role text not null check (role in ('branch_manager','operations_manager','sales_representative','counter_sales','driver')), primary key(company_id,user_id));
create table invitations (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), email text not null, role text not null check (role in ('branch_manager','operations_manager','sales_representative','counter_sales','driver')), invited_by uuid not null references users(id), token_hash text not null unique, expires_at timestamptz not null, accepted_at timestamptz, revoked_at timestamptz, created_at timestamptz default now());
create table contacts (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), company_name text not null, contact_name text, address text, phone text, notes text);
create table requests (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid references branches(id), created_by uuid not null references users(id), type text not null check (type in ('pickup','delivery')), customer text not null, address text not null, priority text not null default 'normal', status text not null default 'pending', assigned_route_id uuid, created_at timestamptz default now());
create table routes (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), branch_id uuid not null references branches(id), driver_id uuid references users(id), route_date date not null, mode text not null default 'locked' check (mode in ('locked','flexible')), status text not null default 'draft', created_at timestamptz default now());
create table route_stops (id uuid primary key default gen_random_uuid(), route_id uuid not null references routes(id), contact_id uuid references contacts(id), type text not null check (type in ('pickup','delivery','return')), position int not null, status text not null default 'pending', po text, notes text, completed_at timestamptz, completion_lat numeric, completion_lng numeric, completion_accuracy_m numeric, completion_method text not null default 'gps' check (completion_method in ('gps','photo_override','signature','manager_override')), issue_reason text, issue_photo_url text, completion_photo_url text);
create table packing_lists (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), route_id uuid references routes(id), stop_id uuid references route_stops(id), file_url text not null, file_type text not null check (file_type in ('pdf','image')), visible_to_driver boolean not null default true, visible_to_customer boolean not null default false, created_by uuid references users(id), created_at timestamptz default now());
create table activity_logs (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id), user_id uuid references users(id), action text not null, record_id uuid, before_value jsonb, after_value jsonb, created_at timestamptz default now());

-- En producción: activar RLS y permitir crear/revocar invitations solo a Branch Manager.
alter table invitations enable row level security;
create policy "managers_manage_invitations" on invitations for all using (exists (select 1 from company_users cu where cu.company_id = invitations.company_id and cu.user_id = auth.uid() and cu.role = 'branch_manager'));
