'use client'
import Link from 'next/link'
import {useCallback,useEffect,useRef,useState} from 'react'
import {getSupabase} from '../../lib/supabase'
import {completeMission} from '../../lib/data'
import {getCurrentLocation} from '../../lib/location'
import {uploadMissionEvidence} from '../../lib/mission-evidence'
import {getLocale,translations,type Locale} from '../../lib/i18n'

type Mission={id:string;status:string;origin_address?:string;destination_address?:string;destination_name?:string;priority?:string;notes?:string;position:number}
function MapPreview({address}:{address?:string}){if(!address)return null;return <div className="embedded-map"><iframe title="Route map" src={`https://www.google.com/maps?q=${encodeURIComponent(address)}&output=embed`} loading="lazy"/><a className="map-fallback" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`} target="_blank" rel="noreferrer">Open in Google Maps</a></div>}
export default function Driver(){const[m,setM]=useState<Mission[]>([]),[msg,setMsg]=useState(''),[modal,setModal]=useState(false),[photo,setPhoto]=useState<File|null>(null),[note,setNote]=useState(''),[locale,setLocale]=useState<Locale>('en');const file=useRef<HTMLInputElement>(null),t=translations[locale]
 const load=useCallback(async()=>{try{const s=getSupabase(),{data:u}=await s.auth.getUser();if(!u.user)throw Error(t.signIn);const{data,error}=await s.from('routes').select('id,status,origin_address,destination_address,destination_name,priority,notes,position').eq('driver_id',u.user.id).in('status',['published','active','paused']).order('position');if(error)throw error;setM(data||[]);setMsg('')}catch(e){setMsg(e instanceof Error?e.message:'Unable to load routes.')}},[t.signIn])
 useEffect(()=>{setLocale(getLocale());load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[load])
 const cur=m[0],next=m[1]
 const update=async(status:string)=>{if(!cur)return;try{if(status==='completed'){if(!photo){file.current?.click();return}await uploadMissionEvidence(photo,cur.id);await completeMission(cur.id)}else{const{error}=await getSupabase().from('routes').update({status,notes:status==='issue'?note:undefined,updated_version:Date.now()}).eq('id',cur.id);if(error)throw error}setModal(false);setPhoto(null);setNote('');await load()}catch(e){setMsg(e instanceof Error?e.message:'Unable to update route.')}}
 return <main className="app"><header className="topbar"><Link className="brand" href="/">ROUTEHUB</Link><div className="avatar">DR</div></header><p className="muted">{t.driverWorkspace}</p><h1>{t.routes}</h1>{msg&&<p className="muted" role="status">{msg}</p>}{cur?<><section className="card"><small className="muted">{t.currentRoute} · {cur.priority||'normal'}</small><h2>{cur.destination_name||cur.destination_address||t.destination}</h2><p className="muted">{cur.origin_address||t.origin} → {cur.destination_address||t.destination}</p><MapPreview address={cur.destination_address}/>{cur.notes&&<p>{cur.notes}</p>}<div className="actions"><a className="primary" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(cur.destination_address||'')}`} target="_blank" rel="noreferrer">{t.navigate}</a>{cur.status==='published'&&<button className="secondary" onClick={()=>update('active')}>{t.start}</button>}{cur.status==='active'&&<><button className="primary" onClick={()=>setModal(true)}>{t.complete}</button><button className="secondary" onClick={()=>update('paused')}>{t.pause}</button></>}{cur.status==='paused'&&<button className="primary" onClick={()=>update('active')}>{t.resume}</button>}</div></section><section className="card" style={{marginTop:16}}><small className="muted">{t.nextRoute}</small><h2>{next?.destination_name||next?.destination_address||t.noNext}</h2></section></>:!msg&&<section className="card"><h2>{t.noRoute}</h2></section>}{modal&&<div className="modal-backdrop"><div className="card modal"><button className="close" onClick={()=>setModal(false)}>×</button><h2>{t.complete}</h2><p className="muted">{t.photo}</p><input ref={file} hidden type="file" accept="image/*" capture="environment" onChange={e=>setPhoto(e.target.files?.[0]||null)}/><button className="success" onClick={()=>photo?update('completed'):file.current?.click()}>{photo?t.completeWithPhoto:t.addPhoto}</button><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder={t.reason}/><button className="danger-outline" disabled={!note.trim()} onClick={()=>update('issue')}>{t.couldNotDeliver}</button></div></div>}<nav className="nav"><Link href="/driver">{t.home}</Link><Link href="/driver/history">{t.history}</Link><Link href="/driver/settings">{t.settings}</Link></nav></main>
}
