'use client'
import Link from 'next/link'
import { useCallback, useEffect, useRef, useState } from 'react'
import { getSupabase } from '../../lib/supabase'
import { completeMission } from '../../lib/data'
import { getCurrentLocation } from '../../lib/location'
import { uploadMissionEvidence } from '../../lib/mission-evidence'
import { getLocale, translations, type Locale } from '../../lib/i18n'
type Mission={id:string;status:string;origin_address?:string;destination_address?:string;destination_name?:string;priority?:string;notes?:string;position:number}
export default function Driver(){const[missions,setMissions]=useState<Mission[]>([]),[msg,setMsg]=useState(''),[photo,setPhoto]=useState<File|null>(null),[modal,setModal]=useState(false),[reporting,setReporting]=useState(false),[note,setNote]=useState(''),[locale,setLocale]=useState<Locale>('en');const fileRef=useRef<HTMLInputElement>(null),t=translations[locale]
 const load=useCallback(async()=>{try{const s=getSupabase();const{data:u}=await s.auth.getUser();if(!u.user)throw Error(t.signIn);const{data,error}=await s.from('routes').select('id,status,origin_address,destination_address,destination_name,priority,notes,position').eq('driver_id',u.user.id).in('status',['published','active','paused']).order('position');if(error)throw error;setMissions(data||[]);setMsg('')}catch(e){setMsg(e instanceof Error?e.message:'Unable to load routes.')}},[t.signIn])
 useEffect(()=>{setLocale(getLocale());load();if(!localStorage.getItem('routehub_location_prompted'))getCurrentLocation().catch(()=>{}).finally(()=>localStorage.setItem('routehub_location_prompted','1'));const timer=setInterval(load,30000);return()=>clearInterval(timer)},[load])
 const cur=missions[0],next=missions[1]
 const update=async(status:string)=>{if(!cur)return;try{if(status==='completed'){if(!photo){fileRef.current?.click();return}try{await uploadMissionEvidence(photo,cur.id)}catch{setMsg('Route completed, but photo upload failed.')}await completeMission(cur.id)}else{const{error}=await getSupabase().from('routes').update({status,notes:status==='issue'?note:undefined,updated_version:Date.now()}).eq('id',cur.id);if(error)throw error}setModal(false);setReporting(false);setNote('');setPhoto(null);await load()}catch(e){setMsg(e instanceof Error?e.message:'Unable to update route.')}}
 return <main className="app"><header className="topbar"><Link className="brand" href="/">ROUTEHUB</Link><div className="avatar">DR</div></header><p className="muted">{t.driverWorkspace}</p><h1>{t.routes}</h1>{msg&&<p className="muted" role="status">{msg}</p>}{cur?<><section className="card"><small className="muted">{t.currentRoute} · {cur.priority||'normal'}</small><h2>{cur.destination_name||cur.destination_address||t.destination}</h2><p className="muted">{cur.origin_address||t.origin} → {cur.destination_address||t.destination}</p>{cur.notes&&<p>{cur.notes}</p>}<div className="actions"><a className="primary" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(cur.destination_address||'')}`} target="_blank" rel="noreferrer">{t.navigate}</a>{cur.status==='published'&&<button className="secondary" onClick={()=>update('active')}>{t.start}</button>}{cur.status==='active'&&<><button className="primary" onClick={()=>setModal(true)}>{t.complete}</button><button className="secondary" onClick={()=>update('paused')}>{t.pause}</button></>}{cur.status==='paused'&&<button className="primary" onClick={()=>update('active')}>{t.resume}</button>}</div></section><section className="card" style={{marginTop:16}}><small className="muted">{t.nextRoute}</small><h2>{next?.destination_name||next?.destination_address||t.noNext}</h2></section></>:!msg&&<section className="card"><h2>{t.noRoute}</h2></section>}{modal&&<div className="modal-backdrop"><div className="card modal" role="dialog" aria-modal="true"><button aria-label={t.cancel} className="close" onClick={()=>{setModal(false);setReporting(false)}}>×</button>{!reporting?<><h2>{t.complete}</h2><p className="muted">{t.photo}</p><input ref={fileRef} hidden type="file" accept="image/*" capture="environment" onChange={e=>setPhoto(e.target.files?.[0]||null)}/><div className="actions"><button className="success" onClick={()=>photo?update('completed'):fileRef.current?.click()}>{photo?t.completeWithPhoto:t.addPhoto}</button></div><button className="danger-outline" onClick={()=>setReporting(true)}>{t.couldNotDeliver}</button></>:<><h2>{t.reportProblem}</h2><p className="muted">{t.reason}</p><textarea autoFocus value={note} onChange={e=>setNote(e.target.value)} placeholder={t.reason}/><button className="danger" disabled={!note.trim()} onClick={()=>update('issue')}>{t.saveIssue}</button></>}</div></div>}<nav className="nav"><Link href="/driver">{t.home}</Link><Link href="/driver/history">{t.history}</Link><Link href="/driver/settings">{t.settings}</Link></nav></main>}
