'use client'
import Link from 'next/link'
import {useEffect,useState} from 'react'
import {ArrowDown,ArrowUp,GripVertical,Plus,AlertTriangle} from 'lucide-react'
import {getSupabase} from '../../../lib/supabase'
import {reorder,insertUrgent,canMove,type Mission} from '../../../lib/planner'

export default function ManageRoutes(){
  const [missions,setMissions]=useState<Mission[]>([]),[message,setMessage]=useState('Loading routes…'),[dragged,setDragged]=useState<number|null>(null)
  const load=async()=>{try{const s=getSupabase(),{data:user}=await s.auth.getUser();if(!user.user)throw Error('Sign in to view routes.');const{data:m}=await s.from('company_users').select('company_id').eq('user_id',user.user.id).limit(1).maybeSingle();if(!m)throw Error('No company membership.');const{data,error}=await s.from('routes').select('id,status,position,origin_address,destination_address,priority,mission_type').eq('company_id',m.company_id).order('position');if(error)throw error;setMissions((data||[]).map((r:any)=>({id:r.id,type:r.mission_type||'delivery',status:r.status||'pending',origin:r.origin_address||'Branch',destination:r.destination_address||'Destination',priority:r.priority||'normal',position:r.position||1})));setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'Unable to load routes.')}}
  useEffect(()=>{load()},[])
  const persist=async(next:Mission[])=>{setMissions(next);const s=getSupabase();await Promise.all(next.map(m=>s.from('routes').update({position:m.position,origin_address:m.origin,status:m.status,priority:m.priority}).eq('id',m.id)))}
  const move=(from:number,to:number)=>{if(from===to||!missions[from]||!canMove(missions[from].status))return;const next=reorder(missions,from,to);if(next!==missions)persist(next)}
  const urgent=()=>persist(insertUrgent(missions,{id:`urgent-${Date.now()}`,type:'return',status:'pending',origin:'Current location',destination:'Branch',priority:'urgent',position:1}))
  return <main className="app"><header className="topbar"><Link className="brand" href="/">ROUTEHUB</Link><Link className="secondary" href="/routes">Add route</Link></header><p className="muted">Manager · Dispatch</p><div className="manage-heading"><div><h1>Manage routes</h1><p className="muted">Drag a pending route to change its order. Completed routes stay locked.</p></div><button className="secondary urgent-button" onClick={urgent}><AlertTriangle size={16}/>Urgent route</button></div>{message&&<p className="muted" role="status">{message}</p>}<section className="route-list">{missions.map((m,i)=>{const movable=canMove(m.status);return <article className={`card route-card ${m.priority==='urgent'?'route-urgent':''} ${movable?'route-movable':''}`} key={m.id} draggable={movable} onDragStart={()=>setDragged(i)} onDragOver={e=>{if(movable||dragged!==null)e.preventDefault()}} onDrop={()=>{if(dragged!==null){move(dragged,i);setDragged(null)}}}><div className="route-grip" aria-label={movable?'Drag to reorder':'Completed route locked'}><GripVertical size={20}/></div><div className="route-content"><div className="route-meta"><span>Route {m.position} · {m.type.toUpperCase()}</span>{m.priority==='urgent'&&<b className="urgent-label">URGENT</b>}</div><h2>{m.origin} → {m.destination}</h2><span className={`route-status status-${m.status}`}>{m.status}</span></div><div className="route-actions"><button className="secondary icon-button" aria-label="Move up" disabled={!movable||i===0} onClick={()=>move(i,i-1)}><ArrowUp size={16}/></button><button className="secondary icon-button" aria-label="Move down" disabled={!movable||i===missions.length-1} onClick={()=>move(i,i+1)}><ArrowDown size={16}/></button></div></article>})}{!missions.length&&!message&&<section className="card"><h2>No routes yet</h2><p className="muted">Create a route to start dispatching.</p></section>}</section><Link className="primary add-route-button" href="/routes"><Plus size={17}/>Add route</Link></main>
}
