'use client'
import {FormEvent,useEffect,useState} from 'react'
import Link from 'next/link'
import {ArrowLeft,Truck,Briefcase,Shield,ChevronRight,Globe,Moon,Sun} from 'lucide-react'
import {getAccessProfile,AccessProfile} from '../../../lib/access'
import {getMembership} from '../../../lib/data'

export default function Settings(){
 const[sent,setSent]=useState(false),[access,setAccess]=useState<AccessProfile|null>(null),[profile,setProfile]=useState<any>(null),[branch,setBranch]=useState<any>(null),[branchName,setBranchName]=useState(''),[branchAddress,setBranchAddress]=useState(''),[language,setLanguage]=useState('English'),[theme,setTheme]=useState('auto')
 useEffect(()=>{getAccessProfile().then(setAccess).catch(()=>setAccess(null));getMembership().then(async({client,membership,user})=>{setProfile(user);if(membership.branch_id){const r=await client.from('branches').select('id,name,address').eq('id',membership.branch_id).maybeSingle();if(r.data){setBranch(r.data);setBranchName(r.data.name||'');setBranchAddress(r.data.address||'')}}}).catch(()=>{});setLanguage(localStorage.getItem('routehub-language')||'English');setTheme(localStorage.getItem('routehub-theme')||'auto')},[])
 const saveBranch=async()=>{if(!branchAddress.trim()||!branch)return;const{client}=await getMembership();const r=await client.from('branches').update({name:branchName,address:branchAddress}).eq('id',branch.id);if(!r.error){setBranch({...branch,name:branchName,address:branchAddress});setSent(true)}}
 const changeTheme=(value:string)=>{setTheme(value);localStorage.setItem('routehub-theme',value);const dark=value==='dark'||(value==='auto'&&window.matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',dark)}
 const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)}
 return <main className="shell settings-page"><button className="back-button" onClick={()=>history.back()}><ArrowLeft/>Settings</button>
 {access?.isCeo?<><h1>Roles and administration</h1><p className="muted">Manage access and permissions for your company.</p><h2>Roles</h2><div className="role-list"><Link href="/driver"><span className="role-icon"><Truck/></span><span><b>Driver</b><small>Driver role</small></span><ChevronRight/></Link><Link href="/manager"><span className="role-icon"><Briefcase/></span><span><b>Manager</b><small>Management and supervision</small></span><ChevronRight/></Link><Link href="/admin"><span className="role-icon"><Shield/></span><span><b>CEO / Admin</b><small>Full administration</small></span><ChevronRight/></Link></div></>:<><h1>Settings</h1><p className="muted">Your preferences and support.</p></>}
 {(access?.canManageRoutes||access?.isCeo)&&branch&&<section className="card settings-section"><h2>Branch setup</h2><p className="muted">Set this address once. It becomes the default starting point for new routes.</p><label>Branch name<input value={branchName} onChange={e=>setBranchName(e.target.value)}/></label><label>Branch address<input value={branchAddress} onChange={e=>setBranchAddress(e.target.value)} placeholder="Full branch address"/></label><button className="primary" onClick={saveBranch}>Save branch address</button></section>}<section className="card settings-section"><h2>Profile</h2><p><strong>{profile?.user_metadata?.full_name||profile?.user_metadata?.name||'RouteHub user'}</strong></p><p className="muted">{profile?.email||'Email not available'}</p></section>
 {(access?.canManageRoutes||access?.isCeo)&&<section className="card settings-section"><h2><Briefcase size={20}/>Manage team and branch</h2><p className="muted">Add, edit, invite, or revoke employees in your branch.</p><Link className="primary" href="/manager/team">Manage team</Link></section>}
 <section className="card settings-section"><h2><Globe size={20}/>Language</h2><p className="muted">Choose the language for your interface.</p><select value={language} onChange={e=>{setLanguage(e.target.value);localStorage.setItem('routehub-language',e.target.value)}}><option>English</option><option>Espa&#241;ol</option><option>Fran&#231;ais</option></select></section>
 <section className="card settings-section"><h2>{theme==='dark'?<Moon size={20}/>:<Sun size={20}/>}Theme</h2><p className="muted">Choose automatic, light, or dark mode.</p><select value={theme} onChange={e=>changeTheme(e.target.value)}><option value="auto">Automatic</option><option value="light">Light</option><option value="dark">Dark</option></select></section>
 <h2>Support</h2><section className="card contact-panel"><h2>Contact RouteHub</h2><p className="muted">Report an issue, missing feature, or idea.</p>{sent?<p className="label">Message sent. We will follow up.</p>:<form className="form" onSubmit={submit}><select><option>Problem or issue</option><option>Missing feature</option><option>Question</option><option>Suggestion</option></select><input required placeholder="Subject"/><textarea required placeholder="Describe what you need" rows={4}/><button className="primary">Send message</button></form>}</section></main>
}
