'use client'
export const dynamic = 'force-dynamic'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { getSupabase } from '../../lib/supabase'

export default function Routes(){
 const [form,setForm]=useState({type:'delivery',origin:'Branch',destination:'',priority:'normal',notes:'',scheduled_at:'',driver_id:''}),[contacts,setContacts]=useState<any[]>([]),[drivers,setDrivers]=useState<any[]>([]),[message,setMessage]=useState('')
 useEffect(()=>{(async()=>{const s=getSupabase();const{data:user}=await s.auth.getUser();if(!user.user)return;const{data:m}=await s.from('company_users').select('company_id').eq('user_id',user.user.id).limit(1).maybeSingle();if(!m)return;const[c,d]=await Promise.all([s.from('contacts').select('id,company_name,address').eq('company_id',m.company_id).order('company_name'),s.from('company_users').select('user_id,role,users(email)').eq('company_id',m.company_id).in('role',['driver','branch_manager'])]);setContacts(c.data||[]);setDrivers(d.data||[])})().catch(()=>setMessage('Unable to load route options.'))},[])
 const save=async()=>{if(!form.destination||!form.driver_id){setMessage('Choose a destination and Driver.');return}try{const s=getSupabase();const{data:user}=await s.auth.getUser();if(!user.user)throw Error('Sign in first.');const{data:m}=await s.from('company_users').select('company_id,branch_id').eq('user_id',user.user.id).limit(1).maybeSingle();if(!m)throw Error('No company membership.');const contact=contacts.find(c=>c.id===form.destination);const{error}=await s.from('routes').insert({company_id:m.company_id,branch_id:m.branch_id,driver_id:form.driver_id,route_date:new Date().toISOString().slice(0,10),mode:'flexible',status:'published',mission_type:form.type,origin_name:'Branch',origin_address:form.origin,destination_name:contact?.company_name||form.destination,destination_address:contact?.address||form.destination,priority:form.priority,notes:form.notes,scheduled_at:form.scheduled_at||null,position:1});if(error)throw error;setMessage('Route published.');setForm({...form,destination:'',notes:''})}catch(e){setMessage(e instanceof Error?e.message:'Unable to save route.')}}
 return <main className="app"><header className="topbar"><Link className="brand" href="/">ROUTEHUB</Link><Link className="secondary" href="/routes/manage">Manage routes</Link></header><h1>Add route</h1><p className="muted">Each pickup or delivery is an independent mission.</p><section className="card" style={{display:'grid',gap:12,marginTop:22}}><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="pickup">Pickup</option><option value="delivery">Delivery</option><option value="transfer">Transfer</option><option value="return">Return to branch</option></select></label><label>Driver<select value={form.driver_id} onChange={e=>setForm({...form,driver_id:e.target.value})}><option value="">Choose Driver</option>{drivers.map(d=><option key={d.user_id} value={d.user_id}>{d.users?.email||d.user_id}</option>)}</select></label><label>Starting point<input value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}/></label><label>Contact or destination<input list="routehub-contacts" value={contacts.find(c=>c.id===form.destination)?.company_name||form.destination} placeholder="Search contact or type an address" onChange={e=>{const value=e.target.value;const match=contacts.find(c=>`${c.company_name} · ${c.address}`===value||c.company_name===value||c.address===value);setForm({...form,destination:match?.id||value})}}/><datalist id="routehub-contacts">{contacts.map(c=><option key={c.id} value={`${c.company_name} · ${c.address}`}/>)}</datalist></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="normal">Normal</option><option value="priority">Priority</option><option value="urgent">Urgent</option></select></label><label>Scheduled time<input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><label>Notes<textarea rows={4} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary" onClick={save}>Publish route</button>{message&&<p className="muted" role="status">{message}</p>}</section></main>
}
