'use client'

import Link from 'next/link'
import {useCallback, useEffect, useMemo, useState} from 'react'
import {BarChart3, CalendarDays, CheckCircle2, Clock3, Download, FileText, Printer, TriangleAlert, XCircle} from 'lucide-react'
import {currentMembership} from '../../lib/data'
import {getSupabase} from '../../lib/supabase'
import {useLocale} from '../../lib/use-preferences'
import ManagerShell from '../manager/manager-shell'
import styles from './reports.module.css'

type ReportRoute = {id: string; status: string; mission_type?: string | null; driver_id?: string | null; route_date?: string | null; created_at?: string | null; route_started_at?: string | null; route_completed_at?: string | null}
type Activity = {id: string; action: string; created_at: string; user_id: string; record_id?: string | null}
type Period = 'today' | '7d' | '30d' | 'custom'

const copy = {
  en: {title: 'Reports', subtitle: 'A clear view of pickup and delivery operations.', manager: 'Branch Manager', back: 'Today', today: 'Today', seven: '7 days', thirty: '30 days', custom: 'Custom', from: 'From', to: 'To', allDrivers: 'All drivers', total: 'Total routes', completed: 'Completed', issues: 'Issues', cancelled: 'Cancelled', avgDuration: 'Average route duration', noDuration: 'No completed routes with both timestamps yet.', breakdown: 'Operation breakdown', deliveries: 'Deliveries', pickups: 'Pickups', returns: 'Returns', completion: 'Completion status', activity: 'Recent activity', export: 'Export activity CSV', print: 'Print / PDF', noRoutes: 'No routes in this period.', noActivity: 'No activity yet', activityHelp: 'Route activity will appear here.', route: 'route', routes: 'routes', started: 'Started', completedAt: 'Completed', duration: 'Duration', teamMember: 'Team member', record: 'Record', action: 'Action', loading: 'Loading reports…', unable: 'Unable to load reports.'},
  es: {title: 'Reportes', subtitle: 'Una vista clara de las operaciones de recogida y entrega.', manager: 'Manager de sucursal', back: 'Hoy', today: 'Hoy', seven: '7 días', thirty: '30 días', custom: 'Personalizado', from: 'Desde', to: 'Hasta', allDrivers: 'Todos los conductores', total: 'Rutas totales', completed: 'Completadas', issues: 'Incidencias', cancelled: 'Canceladas', avgDuration: 'Duración promedio de ruta', noDuration: 'Aún no hay rutas completadas con ambos timestamps.', breakdown: 'Desglose operativo', deliveries: 'Entregas', pickups: 'Recogidas', returns: 'Regresos', completion: 'Estado de finalización', activity: 'Actividad reciente', export: 'Exportar actividad CSV', print: 'Imprimir / PDF', noRoutes: 'No hay rutas en este periodo.', noActivity: 'Aún no hay actividad', activityHelp: 'La actividad de rutas aparecerá aquí.', route: 'ruta', routes: 'rutas', started: 'Iniciada', completedAt: 'Completada', duration: 'Duración', teamMember: 'Miembro del equipo', record: 'Registro', action: 'Acción', loading: 'Cargando reportes…', unable: 'No se pudieron cargar los reportes.'},
  fr: {title: 'Rapports', subtitle: 'Une vue claire des opérations de collecte et livraison.', manager: 'Manager de succursale', back: "Aujourd’hui", today: "Aujourd’hui", seven: '7 jours', thirty: '30 jours', custom: 'Personnalisé', from: 'Du', to: 'Au', allDrivers: 'Tous les conducteurs', total: 'Itinéraires totaux', completed: 'Terminés', issues: 'Incidents', cancelled: 'Annulés', avgDuration: 'Durée moyenne', noDuration: 'Aucun itinéraire avec les deux horodatages.', breakdown: 'Répartition opérationnelle', deliveries: 'Livraisons', pickups: 'Collectes', returns: 'Retours', completion: 'Statut de finalisation', activity: 'Activité récente', export: 'Exporter l’activité CSV', print: 'Imprimer / PDF', noRoutes: 'Aucun itinéraire pour cette période.', noActivity: 'Aucune activité', activityHelp: 'L’activité apparaîtra ici.', route: 'itinéraire', routes: 'itinéraires', started: 'Démarré', completedAt: 'Terminé', duration: 'Durée', teamMember: 'Membre de l’équipe', record: 'Enregistrement', action: 'Action', loading: 'Chargement des rapports…', unable: 'Impossible de charger les rapports.'},
} as const
type Copy = (typeof copy)[keyof typeof copy]

const actionNames: Record<string, string> = {route_created: 'Route created', route_updated: 'Route updated', route_started: 'Route started', route_paused: 'Route paused', routes_reordered: 'Routes reordered', delivery_completed: 'Delivery completed'}
function parseDate(value?: string | null) { if (!value) return null; const date = new Date(value.length === 10 ? `${value}T12:00:00` : value); return Number.isNaN(date.getTime()) ? null : date }
function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` }
function durationMinutes(route: ReportRoute) { const start = parseDate(route.route_started_at)?.getTime(); const end = parseDate(route.route_completed_at)?.getTime(); return start != null && end != null && end >= start ? Math.round((end - start) / 60000) : null }
function durationLabel(minutes: number) { return minutes < 60 ? `${minutes} min` : `${Math.floor(minutes / 60)}h${minutes % 60 ? ` ${minutes % 60}min` : ''}` }
function typeKey(value?: string | null) { return value === 'pickup' || value === 'delivery' || value === 'return' ? value : '' }

export default function Reports() {
  const {locale} = useLocale(); const c = copy[locale]
  const [routes, setRoutes] = useState<ReportRoute[]>([]); const [activity, setActivity] = useState<Activity[]>([]); const [people, setPeople] = useState<Record<string, string>>({}); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('')
  const [period, setPeriod] = useState<Period>('30d'); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [driverId, setDriverId] = useState('')
  const load = useCallback(async () => { setLoading(true); try { const membership = await currentMembership(); const client = getSupabase(); let routeQuery = client.from('routes').select('id,status,mission_type,driver_id,route_date,created_at,route_started_at,route_completed_at').eq('company_id', membership.company_id); if (membership.branch_id) routeQuery = routeQuery.eq('branch_id', membership.branch_id); const activityQuery = client.from('activity_logs').select('id,action,created_at,user_id,record_id').eq('company_id', membership.company_id).order('created_at', {ascending: false}).limit(200); const [{data: routeData, error: routeError}, {data: activityData, error: activityError}] = await Promise.all([routeQuery.limit(500), activityQuery]); if (routeError) throw routeError; if (activityError) throw activityError; const rows = (routeData || []) as ReportRoute[]; setRoutes(rows); setActivity((activityData || []) as Activity[]); const ids = [...new Set(rows.map(row => row.driver_id).filter((id): id is string => Boolean(id)))]; if (ids.length) { const {data: members} = await client.from('company_users').select('user_id,users(email)').eq('company_id', membership.company_id).in('user_id', ids); const labels: Record<string, string> = {}; (members || []).forEach((member: {user_id: string; users?: {email?: string | null} | {email?: string | null}[] | null}) => { const user = Array.isArray(member.users) ? member.users[0] : member.users; labels[member.user_id] = user?.email || c.teamMember }); setPeople(labels) } else setPeople({}); setMessage('') } catch (error) { setMessage(error instanceof Error ? error.message : c.unable) } finally { setLoading(false) } }, [c.teamMember, c.unable])
  useEffect(() => { void load() }, [load])
  const drivers = useMemo(() => Object.entries(people).sort((a, b) => a[1].localeCompare(b[1])), [people])
  const filtered = useMemo(() => { const now = new Date(); const today = dateKey(now); const start = new Date(now); start.setHours(0, 0, 0, 0); if (period === '7d') start.setDate(start.getDate() - 6); if (period === '30d') start.setDate(start.getDate() - 29); return routes.filter(route => { const date = parseDate(route.route_date || route.route_completed_at || route.created_at); const key = date ? dateKey(date) : ''; if (period === 'today' && key !== today) return false; if ((period === '7d' || period === '30d') && (!date || date < start)) return false; if (period === 'custom' && ((from && key < from) || (to && key > to))) return false; return !driverId || route.driver_id === driverId }) }, [driverId, from, period, routes, to])
  const durationValues = filtered.map(durationMinutes).filter((value): value is number => value != null); const average = durationValues.length ? Math.round(durationValues.reduce((sum, value) => sum + value, 0) / durationValues.length) : null
  const breakdown = [{key: 'delivery', label: c.deliveries}, {key: 'pickup', label: c.pickups}, {key: 'return', label: c.returns}].map(item => ({...item, count: filtered.filter(route => typeKey(route.mission_type) === item.key).length})); const maxBreakdown = Math.max(1, ...breakdown.map(item => item.count))
  const exportCsv = () => { const csvCell = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`; const content = [[c.action, c.teamMember, 'Created at', c.record], ...activity.map(row => [actionNames[row.action] || row.action.replaceAll('_', ' '), people[row.user_id] || c.teamMember, row.created_at, row.record_id || ''])].map(row => row.map(csvCell).join(',')).join('\n'); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(new Blob([content], {type: 'text/csv'})); anchor.download = 'routehub-activity.csv'; anchor.click() }
  return <ManagerShell active="reports" roleLabel={c.manager}><div className={styles.page}><header className={styles.header}><div><span className={styles.eyebrow}>OPERATIONS</span><h1>{c.title}</h1><p>{c.subtitle}</p></div><div className={styles.headerActions}><Link href="/manager" className={styles.back}>{c.back}</Link><button type="button" onClick={() => window.print()}><Printer size={16}/>{c.print}</button><button type="button" onClick={exportCsv}><Download size={16}/>CSV</button></div></header>
    <section className={styles.filters}><div className={styles.periods}>{(['today', '7d', '30d', 'custom'] as Period[]).map(value => <button type="button" key={value} className={period === value ? styles.activeFilter : ''} onClick={() => setPeriod(value)}>{value === 'today' ? c.today : value === '7d' ? c.seven : value === '30d' ? c.thirty : c.custom}</button>)}</div>{period === 'custom' && <div className={styles.dateFields}><label>{c.from}<input type="date" value={from} onChange={event => setFrom(event.target.value)}/></label><label>{c.to}<input type="date" value={to} onChange={event => setTo(event.target.value)}/></label></div>}<label className={styles.driverFilter}>{c.allDrivers}<select value={driverId} onChange={event => setDriverId(event.target.value)}><option value="">{c.allDrivers}</option>{drivers.map(([id, email]) => <option key={id} value={id}>{email}</option>)}</select></label></section>
    {message && <p className={styles.message} role="status">{message}</p>}{loading ? <div className={styles.loading}>{c.loading}</div> : <><section className={styles.kpis}><Kpi icon={<BarChart3/>} label={c.total} value={filtered.length}/><Kpi icon={<CheckCircle2/>} label={c.completed} value={filtered.filter(route => route.status === 'completed').length} tone="success"/><Kpi icon={<TriangleAlert/>} label={c.issues} value={filtered.filter(route => route.status === 'issue').length} tone="warning"/><Kpi icon={<Clock3/>} label={c.avgDuration} value={average == null ? '—' : durationLabel(average)} tone="neutral"/></section><div className={styles.columns}><section className={styles.card}><div className={styles.sectionHeading}><h2>{c.breakdown}</h2></div>{breakdown.map(item => <div className={styles.breakdown} key={item.key}><div><span>{item.label}</span><strong>{item.count}</strong></div><div className={styles.bar}><i style={{width: `${(item.count / maxBreakdown) * 100}%`}}/></div></div>)}</section><section className={styles.card}><div className={styles.sectionHeading}><h2>{c.completion}</h2></div><div className={styles.statusList}><StatusRow icon={<CheckCircle2/>} label={c.completed} value={filtered.filter(route => route.status === 'completed').length} tone="success"/><StatusRow icon={<TriangleAlert/>} label={c.issues} value={filtered.filter(route => route.status === 'issue').length} tone="warning"/><StatusRow icon={<XCircle/>} label={c.cancelled} value={filtered.filter(route => route.status === 'cancelled').length} tone="neutral"/></div></section></div><section className={styles.card}><div className={styles.sectionHeading}><h2>{c.activity}</h2><span>{activity.length} {activity.length === 1 ? c.route : c.routes}</span></div>{activity.slice(0, 8).map(row => <div className={styles.activityRow} key={row.id}><FileText size={17}/><div><strong>{actionNames[row.action] || row.action.replaceAll('_', ' ')}</strong><span>{new Date(row.created_at).toLocaleString(locale)} · {people[row.user_id] || c.teamMember}</span></div></div>)}{!activity.length && <p className={styles.emptyText}>{c.noActivity} — {c.activityHelp}</p>}</section>{!filtered.length && <p className={styles.emptyText}>{c.noRoutes}</p>}</>}</div></ManagerShell>
}

function Kpi({icon, label, value, tone = 'blue'}: {icon: React.ReactNode; label: string; value: string | number; tone?: string}) { return <article className={`${styles.kpi} ${styles[`kpi_${tone}`]}`}><span>{icon}</span><strong>{value}</strong><small>{label}</small></article> }
function StatusRow({icon, label, value, tone}: {icon: React.ReactNode; label: string; value: number; tone: string}) { return <div className={styles.statusRow}><span className={styles[`status_${tone}`]}>{icon}</span><b>{label}</b><strong>{value}</strong></div> }
