'use client'
import {useState} from 'react'
import Link from 'next/link'
import DriverV3Shell from '../../../components/driver-v3/DriverV3Shell'
import {useDriverData} from '../../../lib/driver-v3/use-driver-data'
import {markArrived,completeStop} from '../../../lib/driver-v3/actions'
import {openNavigation} from '../../../lib/maps/external-navigation'
import {useRouter,useSearchParams} from 'next/navigation'
const operationLabel=(kind:string)=>kind==='branch'?'RETURN TO BRANCH':kind.toUpperCase()
export default function DriverV3Stop(){const router=useRouter();const params=useSearchParams();const {driverId,loading,error,routes,snapshot,refresh}=useDriverData();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const op=snapshot?.currentOperation;const selectedId=params.get('id');const route=((selectedId?routes.find((r:any)=>r.id===selectedId):undefined)||op?.route) as any;const isCurrent=!selectedId||selectedId===op?.route?.id;const act=async(kind:'arrive'|'complete')=>{if(!op||!isCurrent||busy)return;setBusy(true);setMessage('');try{const ctx={routeId:route.id,driverId,companyId:route.company_id};if(kind==='arrive')await markArrived(ctx);else {await completeStop(ctx);await refresh();router.push('/driver-v3/completed');return}await refresh();setMessage('Arrival recorded.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to update stop.')}finally{setBusy(false)}};const maps=()=>{const url=openNavigation({address:route?.destination_address,coordinate:route?.destination_lat!=null&&route?.destination_lng!=null?{lat:Number(route.destination_lat),lng:Number(route.destination_lng)}:null,label:route?.destination_name});if(url)window.location.assign(url)};return <DriverV3Shell active="route"><Link href="/driver-v3/route" className="muted">‹ My Route</Link>{loading?<section className="card"><p>Loading stop…</p></section>:error?<section className="card"><p>{error}</p></section>:!op?<section className="card"><h2>No current stop</h2><p className="muted">There is no active operation.</p></section>:<><p className="eyebrow">STOP {route.position} · {operationLabel(op.kind||'delivery')}</p><h1 className="title">{route.destination_name||route.destination_address||'Current stop'}</h1><section className="card"><p>{route.destination_address||'Address unavailable'}</p>{route.destination_phone&&<a href={`tel:${route.destination_phone}`}>{route.destination_phone}</a>}{route.order_number&&<p><strong>PO / Order:</strong> {route.order_number}</p>}{route.notes&&<p><strong>Instructions:</strong> {route.notes}</p>}{route.scheduled_at&&<p><strong>Scheduled:</strong> {new Date(route.scheduled_at).toLocaleString()}</p>}<div style={{display:'grid',gap:10,marginTop:18}}><button className="secondary" onClick={maps}>OPEN IN MAPS</button><Link className="secondary" href="/driver-v3/pod" style={{display:"grid",placeItems:"center",textDecoration:"none"}}>PHOTO / NOTES / SIGNATURE</Link><Link className="secondary" href="/driver-v3/issue" style={{display:"grid",placeItems:"center",textDecoration:"none"}}>REPORT AN ISSUE</Link>{!route.arrived_at?<button className="primary" disabled={busy||!isCurrent} onClick={()=>void act('arrive')}>{busy?'Updating…':'ARRIVED AT STOP'}</button>:<button className="primary" disabled={busy||!isCurrent} onClick={()=>void act('complete')}>{busy?'Completing…':`COMPLETE ${operationLabel(op.kind||'delivery')}`}</button>}</div>{message&&<p role="status" className="muted">{message}</p>}</section></>}</DriverV3Shell>}
