'use client'
import Link from 'next/link'
import {useState} from 'react'
import DriverV3Shell from '../../components/driver-v3/DriverV3Shell'
import {useDriverData} from '../../lib/driver-v3/use-driver-data'
import {startRoute,markArrived} from '../../lib/driver-v3/actions'
import {operationalDate} from '../../lib/driver-queue'

export default function DriverV3Page() {
  const {loading,error,snapshot,driverId,refresh,drivingSession}=useDriverData(); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('')
  const route=(snapshot?.currentOperation?.route as any)
  const operate=async()=>{if(!route||busy)return;setBusy(true);setMessage('');try{const ctx={routeId:route.id,driverId,companyId:(route as any).company_id};if(route.status!=='active')await startRoute(ctx,operationalDate());else if(!route.arrived_at)await markArrived(ctx);await refresh();setMessage(route.status!=='active'?'Route started.':'Arrival recorded.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to update operation.')}finally{setBusy(false)}}
  return <DriverV3Shell active="today"><div className="todayPage"><p className="eyebrow">ROUTEHUB DRIVER V3</p><h1 className="title">Today</h1><p className="muted todayIntro">Your next pickup or delivery, in one clear view.</p><section className="card todayDriving"><p className="eyebrow">DRIVING DAY</p><strong>{drivingSession?`Active since ${new Date(drivingSession.started_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}`:"Not started"}</strong>{!drivingSession&&<Link className="secondary" href="/driver-v3/driving-day" style={{display:"grid",placeItems:"center",textDecoration:"none",marginTop:8}}>START DRIVING DAY</Link>}</section>{loading?<section className="card"><p>Loading your operation…</p></section>:error?<section className="card"><h2>Unable to load</h2><p className="muted">{error}</p></section>:<section className="card operation todayOperation"><p className="eyebrow">CURRENT OPERATION</p>{snapshot?.currentOperation?<><h2>{route?.destination_name||route?.destination_address||'Current stop'}</h2><span className={`tag tag-${snapshot.currentOperation.kind.toLowerCase()}`}>{snapshot.currentOperation.kind.toUpperCase()}</span><p className="muted">Stop {route?.position} · {snapshot.currentOperation.completed} of {snapshot.currentOperation.total} completed</p><button className="primary" disabled={busy} onClick={()=>void operate()}>{busy?'Updating…':route?.status!=='active'?'START ROUTE':!route?.arrived_at?'ARRIVED':'OPEN STOP'}</button><div className="todayQuickActions" style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginTop:10}}><Link className="secondary" href="/driver-v3/route" style={{display:"grid",placeItems:"center",textDecoration:"none"}}>Route</Link><Link className="secondary" href="/driver-v3/map" style={{display:"grid",placeItems:"center",textDecoration:"none"}}>Map</Link><Link className="secondary" href="/driver-v3/issue" style={{display:"grid",placeItems:"center",textDecoration:"none"}}>Issue</Link></div><Link className="secondary todayOpenStop" href="/driver-v3/stop" style={{display:'grid',placeItems:'center',textDecoration:'none'}}>Open stop details</Link>{message&&<p role="status" className="muted">{message}</p>}</>:<><h2>No operation today</h2><p className="muted">Your assigned work will appear here.</p></>}</section>}</div></DriverV3Shell>
}
