import {getSupabase} from './supabase'
import type {Role,MissionStatus,Priority,MissionType} from './types'
import {recordActivity} from './activity'
import {getCurrentLocation} from './location'
export async function currentUser(){const{data,error}=await getSupabase().auth.getUser();if(error||!data.user)throw new Error('Not signed in');return data.user}
export async function currentMembership(){const user=await currentUser();const{data,error}=await getSupabase().from('company_users').select('company_id,branch_id,role').eq('user_id',user.id);if(error||!data?.length)throw new Error('No company membership');return data.find((x:any)=>x.role==='driver')||data[0]}
export async function currentAccess(){const user=await currentUser();const s=getSupabase();const[{data:memberships},{data:admin}]=await Promise.all([s.from('company_users').select('company_id,branch_id,role').eq('user_id',user.id),s.from('platform_admins').select('user_id').eq('user_id',user.id).maybeSingle()]);if(admin)return{role:'ceo' as const,isCeo:true,membership:memberships?.[0]||null};const membership=memberships?.find((x:any)=>x.role==='driver')||memberships?.[0];if(!membership)throw new Error('No company membership');return{role:membership.role,membership,isCeo:false}}
export async function listContacts(){const membership=await currentMembership();return getSupabase().from('contacts').select('id,company_name,contact_name,address,phone').eq('company_id',membership.company_id).order('company_name')}
export async function listTeam(){const membership=await currentMembership();return getSupabase().from('company_users').select('user_id,role,branch_id').eq('company_id',membership.company_id)}
export async function inviteMember(email:string,role:Role){const membership=await currentMembership();return getSupabase().from('invitations').insert({email:email.trim().toLowerCase(),role,company_id:membership.company_id,branch_id:membership.branch_id})}
export async function listCompanies(){return getSupabase().from('companies').select('id,name').order('name')}
export async function listBranches(companyId:string){return getSupabase().from('branches').select('id,name,address,company_id').eq('company_id',companyId).order('name')}
export async function createMission(input:{type:MissionType;driver_id:string;origin_address:string;destination_address:string;priority:Priority;status:MissionStatus;order_number?:string;notes?:string;scheduled_at?:string;contact_id?:string}){const membership=await currentMembership();return getSupabase().from('routes').insert({...input,company_id:membership.company_id,branch_id:membership.branch_id,position:1}).select().single()}
export async function updateMission(id:string,patch:Partial<{driver_id:string;status:MissionStatus;priority:Priority;notes:string;position:number}>){const user=await currentUser();const membership=await currentMembership();const result=await getSupabase().from('routes').update(patch).eq('id',id).eq('company_id',membership.company_id).select().single();if(!result.error)await recordActivity({companyId:membership.company_id,userId:user.id,action:'mission_updated',recordId:id,after:patch});return result}
export async function setMissionStatus(id:string,status:MissionStatus){const user=await currentUser();const result=await getSupabase().from('routes').update({status,updated_version:Date.now()}).eq('id',id).eq('driver_id',user.id).select().single();if(result.error)throw result.error;return result.data}
export async function completeMission(id:string){const user=await currentUser();const membership=await currentMembership();let location:{lat:number;lng:number;accuracy:number}|undefined;try{location=await getCurrentLocation()}catch{}const completion={status:'completed',completed_at:new Date().toISOString(),completion_method:location?'gps':'manual',...(location?{completion_lat:location.lat,completion_lng:location.lng,completion_accuracy:location.accuracy}:{})};const result=await getSupabase().from('routes').update(completion).eq('id',id).eq('driver_id',user.id).eq('company_id',membership.company_id).select().single();if(result.error)throw result.error;await recordActivity({companyId:membership.company_id,userId:user.id,action:'delivery_completed',recordId:id,after:{method:completion.completion_method,location:location||null}});return result.data}
export type TeamRole=Role
