import type {Locale} from './i18n'

export function settingsCopy(locale: Locale) {
  if (locale === 'es') {
    return {
      on: 'On',
      off: 'Off',
      alerts: 'Avisos',
      deviceNotifications: 'Notificaciones del dispositivo',
      notificationsHelp: 'Rutas nuevas y cambios aunque la app esté cerrada.',
      notificationsOn: 'Este dispositivo recibirá avisos de rutas.',
      notificationsOff: 'Ya no vas a recibir avisos en este dispositivo.',
      notificationsOffHelp: 'Apágalas en Ajustes de iPhone → RouteHub si siguen activas.',
      shareLocation: 'Compartir ubicación',
      terms: 'Términos de uso',
      privacy: 'Política de privacidad',
      appearance: 'Tema de la app',
      tour: 'Recorrido de la app',
      tourHelp: 'Vuelve a ver la guía rápida de RouteHub.',
      tourAction: 'Ver recorrido',
      versionLabel: 'Versión',
      workspace: 'Espacio de trabajo',
      company: 'Compañía',
      branch: 'Sucursal',
      contactSupport: 'Contactar soporte',
      supportHelp: 'Escríbele directo a soporte de RouteHub. Para cambios de cuenta o camión, habla con tu manager.',
      supportPlaceholder: 'Describe el problema o tu pregunta…',
      supportSend: 'Enviar',
      supportSending: 'Enviando…',
      supportSent: 'Listo, tu mensaje llegó a soporte.',
      signOut: 'Cerrar sesión',
      signOutQ: '¿Cerrar sesión?',
      signOutBody: 'Vas a salir de tu cuenta en este dispositivo.',
      signingOut: 'Cerrando sesión…',
      userGuide: 'Guía de uso',
      userGuideHelp: 'Cómo usar RouteHub, paso a paso, en tu idioma.',
    }
  }
  if (locale === 'fr') {
    return {
      on: 'On',
      off: 'Off',
      alerts: 'Alertes',
      deviceNotifications: 'Notifications de l’appareil',
      notificationsHelp: 'Nouveaux itinéraires et changements même si l’app est fermée.',
      notificationsOn: 'Cet appareil recevra les alertes de routes.',
      notificationsOff: 'Cet appareil ne recevra plus d’alertes.',
      notificationsOffHelp: 'Désactivez-les dans Réglages iPhone → RouteHub si elles restent actives.',
      shareLocation: 'Partager la position',
      terms: 'Conditions d’utilisation',
      privacy: 'Politique de confidentialité',
      appearance: 'Thème de l’app',
      tour: 'Visite de l’application',
      tourHelp: 'Revoir le guide rapide de RouteHub.',
      tourAction: 'Voir la visite',
      versionLabel: 'Version',
      workspace: 'Espace de travail',
      company: 'Entreprise',
      branch: 'Succursale',
      contactSupport: 'Contacter le support',
      supportHelp: 'Écrivez directement au support RouteHub. Pour un changement de compte ou de camion, contactez votre manager.',
      supportPlaceholder: 'Décrivez le problème ou votre question…',
      supportSend: 'Envoyer',
      supportSending: 'Envoi…',
      supportSent: 'Votre message est arrivé au support.',
      signOut: 'Se déconnecter',
      signOutQ: 'Se déconnecter ?',
      signOutBody: 'Vous allez quitter votre compte sur cet appareil.',
      signingOut: 'Déconnexion…',
      userGuide: 'Guide d’utilisation',
      userGuideHelp: 'Comment utiliser RouteHub, étape par étape, dans votre langue.',
    }
  }
  return {
    on: 'On',
    off: 'Off',
    alerts: 'Alerts',
    deviceNotifications: 'Device notifications',
    notificationsHelp: 'New routes and changes even when the app is closed.',
    notificationsOn: 'This device will receive route alerts.',
    notificationsOff: 'This device will no longer receive route alerts.',
    notificationsOffHelp: 'Turn notifications off in iPhone Settings → RouteHub if they stay on.',
    shareLocation: 'Share location',
    terms: 'Terms of Use',
      privacy: 'Privacy Policy',
      appearance: 'App theme',
      tour: 'App tour',
      tourHelp: 'See the RouteHub quick guide again.',
      tourAction: 'View tour',
      versionLabel: 'Version',
      workspace: 'Workspace',
      company: 'Company',
      branch: 'Branch',
      contactSupport: 'Contact support',
      supportHelp: 'Message RouteHub support directly. For account or truck changes, talk to your manager instead.',
      supportPlaceholder: 'Describe the problem or your question…',
      supportSend: 'Send',
      supportSending: 'Sending…',
      supportSent: 'Sent - support has your message.',
      signOut: 'Sign out',
      signOutQ: 'Sign out?',
      signOutBody: 'You will be signed out of this device.',
      signingOut: 'Signing out…',
      userGuide: 'User guide',
      userGuideHelp: 'How to use RouteHub, step by step, in your language.',
  }
}
