export type Locale = 'en' | 'es' | 'fr'

export const translations = {
  en: {home:'Home',routes:'Routes',history:'History',settings:'Settings',driverWorkspace:'Driver workspace',currentRoute:'Current route',nextRoute:'Next route',noRoute:'No route assigned',navigate:'Navigate',start:'Start route',complete:'Complete route',pause:'Pause',resume:'Resume',photo:'Photo evidence',completeWithPhoto:'Complete with photo',couldNotDeliver:'Could not deliver',reportProblem:'Report problem',saveIssue:'Save issue',cancel:'Cancel',signIn:'Sign in to view routes.',loading:'Loading routes…',destination:'Destination',origin:'Origin',noNext:'No next route',reason:'Reason for failed delivery',addPhoto:'Take or choose a photo',completedRoutes:'Completed routes',noHistory:'No route history',historyHelp:'Completed routes will appear here.',profile:'Profile',preferences:'Preferences',theme:'Theme',language:'Language',logout:'Log out',system:'System',editProfile:'Edit profile',driverAccount:'Driver account',issueReported:'Issue reported',notCompleted:'Not completed',needsAttention:'Needs attention',completionTime:'No completion time'},
  es: {home:'Inicio',routes:'Rutas',history:'Historial',settings:'Configuración',driverWorkspace:'Espacio del conductor',currentRoute:'Ruta actual',nextRoute:'Siguiente ruta',noRoute:'No hay ruta asignada',navigate:'Navegar',start:'Comenzar ruta',complete:'Completar ruta',pause:'Pausar',resume:'Reanudar',photo:'Evidencia fotográfica',completeWithPhoto:'Completar con foto',couldNotDeliver:'No se pudo entregar',reportProblem:'Reportar problema',saveIssue:'Guardar problema',cancel:'Cancelar',signIn:'Inicia sesión para ver tus rutas.',loading:'Cargando rutas…',destination:'Destino',origin:'Origen',noNext:'No hay siguiente ruta',reason:'Motivo de la entrega fallida',addPhoto:'Tomar o elegir una foto',completedRoutes:'Rutas completadas',noHistory:'No hay historial de rutas',historyHelp:'Las rutas completadas aparecerán aquí.',profile:'Perfil',preferences:'Preferencias',theme:'Tema',language:'Idioma',logout:'Cerrar sesión',system:'Sistema',editProfile:'Editar perfil',driverAccount:'Cuenta del conductor',issueReported:'Problema reportado',notCompleted:'No completada',needsAttention:'Requiere atención',completionTime:'Sin hora de finalización'},
  fr: {home:'Accueil',routes:'Itinéraires',history:'Historique',settings:'Paramètres',driverWorkspace:'Espace conducteur',currentRoute:'Itinéraire actuel',nextRoute:'Prochain itinéraire',noRoute:'Aucun itinéraire assigné',navigate:'Naviguer',start:'Commencer',complete:'Terminer',pause:'Mettre en pause',resume:'Reprendre',photo:'Preuve photo',completeWithPhoto:'Terminer avec photo',couldNotDeliver:'Livraison impossible',reportProblem:'Signaler un problème',saveIssue:'Enregistrer le problème',cancel:'Annuler',signIn:'Connectez-vous pour voir vos itinéraires.',loading:'Chargement des itinéraires…',destination:'Destination',origin:'Départ',noNext:'Aucun prochain itinéraire',reason:'Motif de l’échec de livraison',addPhoto:'Prendre ou choisir une photo',completedRoutes:'Itinéraires terminés',noHistory:'Aucun historique',historyHelp:'Les itinéraires terminés apparaîtront ici.',profile:'Profil',preferences:'Préférences',theme:'Thème',language:'Langue',logout:'Se déconnecter',system:'Système',editProfile:'Modifier le profil',driverAccount:'Compte conducteur',issueReported:'Problème signalé',notCompleted:'Non terminé',needsAttention:'Attention requise',completionTime:'Aucune heure de fin'}
} as const

export function getLocale(): Locale {
  if (typeof window === 'undefined') return 'en'
  const value = localStorage.getItem('routehub_language') || localStorage.getItem('rh2-language')
  return value === 'es' || value === 'fr' ? value : 'en'
}
