'use client'

import Link from 'next/link'
import {ArrowRight, LoaderCircle, Plus, X} from 'lucide-react'
import {useCallback,useEffect,useState} from 'react'
import {getSupabase} from '../../lib/supabase'
import {useLocale} from '../../lib/use-preferences'
import GoogleAddressInput from '../google-address-input'

type RequestItem={id:string;type:string;customer:string;address:string;priority:string;status:string}

export default function Requests(){
 const {locale,t}=useLocale();const assignCopy={en:'Assign to route',es:'Asignar a una ruta',fr:'Attribuer à un itinéraire'}[locale];const[items,setItems]=useState<RequestItem[]>([]),[tab,setTab]=useState('pending'),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[form,setForm]=useState({type:'pickup',customer:'',address:'',priority:'normal'})
 const load=useCallback(async()=>{try{const client=getSupabase();const{data:userData}=await client.auth.getUser();if(!userData.user)throw Error(t.signIn);const{data:membership}=await client.from('company_users').select('company_id').eq('user_id',userData.user.id).limit(1).maybeSingle();if(!membership)throw Error(t.noMembership);const{data,error}=await client.from('requests').select('id,type,customer,address,priority,status').eq('company_id',membership.company_id).order('created_at',{ascending:false});if(error)throw error;setItems(data||[]);setMessage('')}catch(error){setMessage(error instanceof Error?error.message:t.unableLoadRequests)}},[t])
 useEffect(()=>{void load()},[load])
 const save=async()=>{if(!form.customer.trim()||!form.address.trim()||saving)return;setSaving(true);try{const client=getSupabase();const{data:userData}=await client.auth.getUser();if(!userData.user)throw Error(t.signInFirst);const{data:membership}=await client.from('company_users').select('company_id,branch_id').eq('user_id',userData.user.id).limit(1).maybeSingle();if(!membership)throw Error(t.noMembership);const{error}=await client.from('requests').insert({...form,customer:form.customer.trim(),address:form.address.trim(),company_id:membership.company_id,branch_id:membership.branch_id,created_by:userData.user.id,status:'pending'});if(error)throw error;setMessage(t.requestSaved);setOpen(false);setForm({type:'pickup',customer:'',address:'',priority:'normal'});await load()}catch(error){setMessage(error instanceof Error?error.message:t.unableSaveRequest)}finally{setSaving(false)}}
 const cancelRequest=async(id:string)=>{if(saving)return;setSaving(true);try{const{error}=await getSupabase().from('requests').update({status:'cancelled'}).eq('id',id).eq('status','pending');if(error)throw error;setMessage(t.cancelled);await load()}catch(error){setMessage(error instanceof Error?error.message:t.unableSaveRequest)}finally{setSaving(false)}}
 const visible=items.filter(item=>item.status===tab),statusLabel=(status:string)=>status==='pending'?t.pending:status==='assigned'?t.assigned:status==='completed'?t.completed:t.cancelled,typeLabel=(type:string)=>type==='pickup'?t.pickup:t.delivery
 return <main className="app requests-page"><header className="topbar"><Link className="brand" href="/">ROUTEHUB</Link><button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/>{t.newRequest}</button></header><p className="eyebrow">{t.operations.toUpperCase()}</p><h1>{t.requests}</h1><p className="muted">{t.requestsHelp}</p><div className="request-tabs" role="tablist">{['pending','assigned','completed','cancelled'].map(status=><button className={tab===status?'primary':'secondary'} role="tab" aria-selected={tab===status} key={status} onClick={()=>setTab(status)}>{statusLabel(status)}</button>)}</div>
 {open&&<section className="card compact-form"><div className="form-title"><h2>{t.newRequestTitle}</h2><button className="close" aria-label={t.close} onClick={()=>setOpen(false)}><X/></button></div><label>{t.type}<select value={form.type} onChange={event=>setForm({...form,type:event.target.value})}><option value="pickup">{t.pickup}</option><option value="delivery">{t.delivery}</option></select></label><label>{t.customerSupplier}<input value={form.customer} onChange={event=>setForm({...form,customer:event.target.value})}/></label><label>{t.address}<GoogleAddressInput value={form.address} autoComplete="street-address" onValueChange={value=>setForm(current=>({...current,address:value}))}/></label><label>{t.priorityLabel}<select value={form.priority} onChange={event=>setForm({...form,priority:event.target.value})}><option value="normal">{t.normal}</option><option value="priority">{t.priority}</option><option value="urgent">{t.urgent}</option></select></label><div className="actions"><button className="primary" disabled={saving} onClick={()=>void save()}>{saving?<LoaderCircle className="spin" size={17}/>:null}{saving?t.saving:t.saveRequest}</button><button className="secondary" onClick={()=>setOpen(false)}>{t.cancel}</button></div></section>}
 <section className="request-list">{visible.map(item=><article className={`card request-card priority-${item.priority}`} key={item.id}><small>{typeLabel(item.type).toUpperCase()} · {(item.priority==='urgent'?t.urgent:item.priority==='priority'?t.priority:t.normal).toUpperCase()}</small><h2>{item.customer}</h2><p className="muted">{item.address}</p>{item.status==='pending'&&<div className="request-actions"><Link className="secondary request-assign" href={`/routes?request=${encodeURIComponent(item.id)}&type=${encodeURIComponent(item.type)}&destination=${encodeURIComponent(item.address)}&priority=${encodeURIComponent(item.priority)}`}>{assignCopy}<ArrowRight size={16}/></Link><button className="secondary request-cancel" disabled={saving} onClick={()=>void cancelRequest(item.id)}><X size={15}/>{t.cancel}</button></div>}</article>)}{!visible.length&&<section className="card"><h2>{t.noRequestsPrefix} {statusLabel(tab).toLowerCase()} {t.noRequestsSuffix}</h2><p className="muted">{t.requestsAppear}</p></section>}</section>{message&&<p className="muted" role="status" aria-live="polite">{message}</p>}</main>
}
