'use client'
import {useEffect,useState} from 'react'
import {ArrowRight,CalendarDays,Edit3,GripVertical,MapPin} from 'lucide-react'
import {getMembership} from '../../lib/data'

export default function SavedRoutes(){
  const [routes,setRoutes]=useState<any[]>([]),[error,setError]=useState('')
  const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{try{const {client,membership}=await getMembership();const {data,error}=await client.from('routes').select('id,position,status,route_date,driver_id,origin_name,origin_address,destination_name,destination_address,order_number,priority').eq('company_id',membership.company_id).order('position',{ascending:true}).order('route_date',{ascending:false});if(error)throw error;setRoutes(data||[])}catch(e){setError(e instanceof Error?e.message:'Could not load assigned routes.')}finally{setLoading(false)}})()},[])
  if(loading)return <section className="loading-skeleton"><span/><span/><span/></section>
  if(error)return <section className="empty-state"><h3>Could not load assigned routes</h3><p>{error}</p></section>
 return <section className="configured-routes"><div className="section-head"><div><h2>Assigned routes ({routes.length})</h2><p className="muted">Published and assigned routes for your company.</p></div><a className="assign" href="/routes/manage">Manage</a></div>{routes.length===0?<div className="empty-state"><h3>No assigned routes yet</h3><p>Publish a route to see it here.</p></div>:<div className="saved-route-list">{routes.map((r,i)=>{const destination=r.destination_address||r.destination_name||'';const map=destination?`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(destination)}`:'';return <article className="card saved-route-card" key={r.id}><span className="saved-route-position"><GripVertical size={16}/>{r.position??i+1}</span><div className="saved-route-main"><div className="saved-route-head"><span className={`status-badge ${r.status==='completed'?'status-success':r.status==='cancelled'?'status-danger':'status-info'}`}>{r.status||'draft'}</span><span className="muted"><CalendarDays size={14}/> {r.route_date||'No date'}</span></div><h3>{r.origin_name||r.origin_address||'Origin pending'} <ArrowRight size={16}/> {r.destination_name||r.destination_address||'Destination pending'}</h3><p className="muted">{r.order_number?`PO: ${r.order_number} · `:''}{r.priority||'normal'}</p></div>{map&&<a className="assign" href={map} target="_blank" rel="noreferrer"><MapPin size={15}/> Map</a>}<a className="assign" href="/routes/manage" aria-label={`Edit route ${i+1}`}><Edit3 size={16}/> Edit</a></article>})}</div>}</section>
}
