export const settingsCopy = {
  es: {
    name: 'Nombre completo',
    phone: 'Teléfono',
    photo: 'Cambiar foto',
    edit: 'Editar',
    save: 'Guardar perfil',
    profileSaved: 'Perfil actualizado.',
    branch: 'Sucursal principal',
    branchName: 'Nombre de la sucursal',
    branchAddress: 'Dirección de la sucursal',
    branchPhone: 'Teléfono de la sucursal',
    saveBranch: 'Guardar sucursal',
    branchSaved: 'Sucursal actualizada.',
    noBranch: 'No hay una sucursal asignada.',
    tour: 'Recorrido de la app',
    tourHelp: 'Vuelve a ver la guía rápida de RouteHub.',
    tourAction: 'Ver recorrido',
    appearance: 'Apariencia',
    language: 'Idioma',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    privacy: 'Privacidad',
    terms: 'Términos',
    help: 'Ayuda',
    helpHelp: 'Guía del manager y contacto de soporte.',
    billingHelp: 'Plan actual, prueba y lo que incluye el espacio.',
  },
  fr: {
    name: 'Nom complet',
    phone: 'Téléphone',
    photo: 'Changer la photo',
    edit: 'Modifier',
    save: 'Enregistrer le profil',
    profileSaved: 'Profil mis à jour.',
    branch: 'Succursale principale',
    branchName: 'Nom de la succursale',
    branchAddress: 'Adresse de la succursale',
    branchPhone: 'Téléphone de la succursale',
    saveBranch: 'Enregistrer la succursale',
    branchSaved: 'Succursale mise à jour.',
    noBranch: 'Aucune succursale associée.',
    tour: 'Visite de l’application',
    tourHelp: 'Revoir le guide rapide de RouteHub.',
    tourAction: 'Voir la visite',
    appearance: 'Apparence',
    language: 'Langue',
    light: 'Clair',
    dark: 'Sombre',
    system: 'Système',
    privacy: 'Confidentialité',
    terms: 'Conditions',
    help: 'Aide',
    helpHelp: 'Guide manager et contact assistance.',
    billingHelp: 'Offre actuelle, essai et contenu de l’espace.',
  },
  en: {
    name: 'Full name',
    phone: 'Phone number',
    photo: 'Change photo',
    edit: 'Edit',
    save: 'Save profile',
    profileSaved: 'Profile updated.',
    branch: 'Primary branch',
    branchName: 'Branch name',
    branchAddress: 'Branch address',
    branchPhone: 'Branch phone number',
    saveBranch: 'Save branch',
    branchSaved: 'Branch updated.',
    noBranch: 'No branch assigned.',
    tour: 'App tour',
    tourHelp: 'See the RouteHub quick guide again.',
    tourAction: 'View tour',
    appearance: 'Appearance',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    privacy: 'Privacy',
    terms: 'Terms',
    help: 'Help',
    helpHelp: 'Manager guide and support contact.',
    billingHelp: 'Current plan, trial and what the workspace includes.',
  },
} as const
