'use client'
import {useEffect,useState} from 'react'
import {MapPin,Phone,Plus,UserRound,Trash2} from 'lucide-react'
import {createContact,deleteContact,getMembership,updateContact} from '../../lib/data'
import {getAccessProfile,AccessProfile} from '../../lib/access'
type Contact={id:string;company_name:string;contact_name?:string;address:string;phone?:string}
const blank={company_name:'',contact_name:'',address:'',phone:''}
export default function Contacts(){const[contacts,setContacts]=useState<Contact[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<Contact|null>(null),[open,setOpen]=useState(false),[message,setMessage]=useState(''),[access,setAccess]=useState<AccessProfile|null>(null)
 const load=async()=>{try{const{client,membership}=await getMembership();const r=await client.from('contacts').select('id,company_id,branch_id,company_name,contact_name,address,phone').eq('company_id',membership.company_id).order('company_name');if(r.error)throw r.error;setContacts(r.data||[])}catch(e){setMessage(e instanceof Error?e.message:'Could not load contacts.')}}
 useEffect(()=>{load();getAccessProfile().then(setAccess).catch(()=>{})},[])
 const save=async()=>{if(!form.company_name.trim()||!form.address.trim())return setMessage('Company and address are required.');const r=editing?await updateContact(editing.id,form):await createContact(form);if(r.error)return setMessage(r.error.message);setMessage(editing?'Contact updated.':'Contact added.');setForm(blank);setEditing(null);setOpen(false);load()}
 const canDelete=access?.isCeo||access?.role==='branch_manager'||access?.role==='operations_manager';const remove=async(c:Contact)=>{if(!window.confirm(`Delete ${c.company_name}?`))return;const r=await deleteContact(c.id);if(r.error)return setMessage(r.error.message);setContacts(x=>x.filter(v=>v.id!==c.id));setMessage('Contact deleted.')}
 return <main className="shell contacts-page"><header className="contacts-header"><div><div className="brand">RouteHub</div><h1>Contacts</h1><p className="muted">Your company and customer directory.</p></div><button className="primary" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus size={18}/>Add contact</button></header>{open&&<section className="card form contact-editor"><h2>{editing?'Edit contact':'New contact'}</h2><label>Company<input value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})}/></label><label>Contact person<input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></label><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><div className="card-actions"><button className="primary" onClick={save}>Save contact</button><button className="assign" onClick={()=>setOpen(false)}>Cancel</button></div></section>}<section className="contact-list">{contacts.map(c=><article className="card contact-list-item" key={c.id}><div className="contact-avatar"><UserRound size={22}/></div><div className="contact-main"><h2>{c.company_name}</h2><p>{c.contact_name||'No contact person'}</p><span><MapPin size={15}/>{c.address}</span>{c.phone&&<span><Phone size={15}/>{c.phone}</span>}</div><div className="contact-actions">{c.phone&&<a className="assign" href={`tel:${c.phone}`}>Call</a>}<button className="assign" onClick={()=>{setEditing(c);setForm({company_name:c.company_name,contact_name:c.contact_name||'',address:c.address,phone:c.phone||''});setOpen(true)}}>Edit</button>{canDelete&&<button className="assign danger-action" onClick={()=>remove(c)}><Trash2 size={15}/>Delete</button>}</div></article>)}{!contacts.length&&<div className="empty-state"><UserRound size={28}/><h3>No contacts yet</h3><p>Add your first contact to create pickups and deliveries.</p></div>}</section>{message&&<p className="action-feedback feedback-info" role="status">{message}</p>}</main>}
