'use client'
import {useEffect,useState} from 'react'
import {ArrowLeft,MapPin,Phone,Plus,UserRound} from 'lucide-react'
import {createContact,getMembership,updateContact} from '../../lib/data'

type Contact={id:string;company_name:string;contact_name?:string;address:string;phone?:string}
const blank={company_name:'',contact_name:'',address:'',phone:''}

export default function Contacts(){
  const[contacts,setContacts]=useState<Contact[]>([]),[form,setForm]=useState(blank),[editing,setEditing]=useState<Contact|null>(null),[open,setOpen]=useState(false),[message,setMessage]=useState('')
  const load=async()=>{try{const{client,membership}=await getMembership();const r=await client.from('contacts').select('*').eq('company_id',membership.company_id).order('company_name');if(r.error)throw r.error;setContacts(r.data||[])}catch{setMessage('No se pudieron cargar los contactos.')}}
  useEffect(()=>{load()},[])
  const save=async()=>{if(!form.company_name.trim()||!form.address.trim()){setMessage('Escribe la empresa y la dirección.');return}const r=editing?await updateContact(editing.id,form):await createContact(form);if(r.error){setMessage(r.error.message);return}if(r.data){setContacts(current=>editing?current.map(c=>c.id===editing.id?r.data:c):[...current,r.data])};setMessage(editing?'Contacto actualizado.':'Contacto agregado.');setForm(blank);setEditing(null);setOpen(false);load()}
  return <main className="shell contacts-page"><header className="contacts-header"><div><div className="brand">RouteHub</div><h1>Contactos</h1><p className="muted">Tu agenda de empresas y clientes.</p></div><button className="primary" onClick={()=>{setEditing(null);setForm(blank);setOpen(true)}}><Plus size={18}/>Agregar contacto</button></header>
    {open&&<section className="card form contact-editor"><div className="section-head"><h2>{editing?'Editar contacto':'Nuevo contacto'}</h2><button className="back-button" onClick={()=>setOpen(false)}><ArrowLeft size={16}/>Cerrar</button></div><label>Empresa<input value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})} placeholder="Nombre de la empresa"/></label><label>Persona de contacto<input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})} placeholder="Nombre del contacto"/></label><label>DirecciÃ³n<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="DirecciÃ³n completa"/></label><label>TelÃ©fono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="TelÃ©fono"/></label><button className="primary" onClick={save}>Guardar contacto</button></section>}
    <section className="contact-list">{contacts.map(c=><article className="card contact-list-item" key={c.id}><div className="contact-avatar"><UserRound size={22}/></div><div className="contact-main"><h2>{c.company_name}</h2><p>{c.contact_name||'Sin persona asignada'}</p><span><MapPin size={15}/>{c.address}</span>{c.phone&&<span><Phone size={15}/>{c.phone}</span>}</div><div className="contact-actions">{c.phone&&<a className="assign" href={`tel:${c.phone}`}>Llamar</a>}<button className="assign" onClick={()=>{setEditing(c);setForm({company_name:c.company_name,contact_name:c.contact_name||'',address:c.address,phone:c.phone||''});setOpen(true)}}>Editar</button></div></article>)}{!contacts.length&&<div className="empty-state"><UserRound size={28}/><h3>AÃºn no hay contactos</h3><p>Agrega tu primer contacto para crear pickups y entregas.</p><button className="primary" onClick={()=>setOpen(true)}><Plus size={18}/>Agregar contacto</button></div>}</section>{message&&<p className="action-feedback feedback-info" role="status">{message}</p>}</main>
}
